/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Hello: typeof import('./../components/hello/hello.vue')['default']
    UButton: typeof import('uview-plus/components/u-button/u-button.vue')['default']
    UGap: typeof import('uview-plus/components/u-gap/u-gap.vue')['default']
    UIcon: typeof import('uview-plus/components/u-icon/u-icon.vue')['default']
    ULoadingIcon: typeof import('uview-plus/components/u-loading-icon/u-loading-icon.vue')['default']
    Unocss: typeof import('./../components/unocss/unocss.vue')['default']
    UOverlay: typeof import('uview-plus/components/u-overlay/u-overlay.vue')['default']
    UTransition: typeof import('uview-plus/components/u-transition/u-transition.vue')['default']
  }
}
