/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Hello: typeof import('./../components/hello/hello.vue')['default']
    UButton: typeof import('vk-uview-ui/components/u-button/u-button.vue')['default']
    UIcon: typeof import('vk-uview-ui/components/u-icon/u-icon.vue')['default']
    Unocss: typeof import('./../components/unocss/unocss.vue')['default']
    UToast: typeof import('vk-uview-ui/components/u-toast/u-toast.vue')['default']
  }
}
